"""empty message

Revision ID: 0169e2d50709
Revises: 898fa5e45807
Create Date: 2020-08-25 16:57:50.334328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0169e2d50709'
down_revision = '898fa5e45807'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'contracts', 'tasks', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    # ### end Alembic commands ###
