"""empty message

Revision ID: 12c84692a3a5
Revises: 50ed9a87c695
Create Date: 2020-07-28 12:13:03.795555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12c84692a3a5'
down_revision = '50ed9a87c695'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ideas', sa.Column('creator_involv', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ideas', 'creator_involv')
    # ### end Alembic commands ###
