"""empty message

Revision ID: 176c8ec6af67
Revises: 6a781dfc6b41
Create Date: 2020-07-24 15:51:12.434932

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '176c8ec6af67'
down_revision = '6a781dfc6b41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('objectives', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'objectives')
    # ### end Alembic commands ###
