"""empty message

Revision ID: 18c91c2ca26a
Revises: 2ec1b7b47293
Create Date: 2020-08-23 17:54:51.537055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18c91c2ca26a'
down_revision = '2ec1b7b47293'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('hide', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'hide')
    # ### end Alembic commands ###
