"""empty message

Revision ID: 2ec1b7b47293
Revises: 95f0f4e663a4
Create Date: 2020-08-20 14:30:34.757668

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2ec1b7b47293'
down_revision = '95f0f4e663a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'mark')
    op.drop_column('projects', 'available_actions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('available_actions', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('mark', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
