"""empty message

Revision ID: 4833e3482cf0
Revises: f7f8be7652be
Create Date: 2020-08-26 09:36:59.977567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4833e3482cf0'
down_revision = 'f7f8be7652be'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('hide', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'hide')
    # ### end Alembic commands ###
