"""empty message

Revision ID: 5e990381e7aa
Revises: a55716df6973
Create Date: 2020-08-10 17:31:35.881984

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '5e990381e7aa'
down_revision = 'a55716df6973'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ideas', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ideas', 'projects', ['project_id'], ['id'])
    op.drop_column('profiles', 'mark')
    op.drop_column('projects', 'available_actions')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('available_actions', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('profiles', sa.Column('mark', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'ideas', type_='foreignkey')
    op.drop_column('ideas', 'project_id')
    # ### end Alembic commands ###
