"""empty message

Revision ID: 898fa5e45807
Revises: 18c91c2ca26a
Create Date: 2020-08-25 16:57:21.096794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '898fa5e45807'
down_revision = '18c91c2ca26a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('contracts', sa.Column('project_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'contracts', 'tasks', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.drop_column('contracts', 'project_id')
    # ### end Alembic commands ###
