"""empty message

Revision ID: 943625ce57ec
Revises: 41258131b700
Create Date: 2020-08-20 10:58:45.005134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '943625ce57ec'
down_revision = '41258131b700'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('start_at', sa.DateTime(), nullable=True))
    op.add_column('projects', sa.Column('teoric_finish', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'teoric_finish')
    op.drop_column('projects', 'start_at')
    op.drop_column('projects', 'created_at')
    # ### end Alembic commands ###
