"""empty message

Revision ID: 9ef5545976c2
Revises: 0169e2d50709
Create Date: 2020-08-25 16:59:51.979756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ef5545976c2'
down_revision = '0169e2d50709'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('contracts_ibfk_3', 'contracts', type_='foreignkey')
    op.create_foreign_key(None, 'contracts', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.create_foreign_key('contracts_ibfk_3', 'contracts', 'tasks', ['project_id'], ['id'])
    # ### end Alembic commands ###
