"""empty message

Revision ID: bea3268003d6
Revises: 12c84692a3a5
Create Date: 2020-07-28 15:03:05.882950

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bea3268003d6'
down_revision = '12c84692a3a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ideas', sa.Column('project_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'ideas', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'ideas', type_='foreignkey')
    op.drop_column('ideas', 'project_id')
    # ### end Alembic commands ###
