"""empty message

Revision ID: c6ab1eea3ce8
Revises: 943625ce57ec
Create Date: 2020-08-20 12:59:09.385872

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c6ab1eea3ce8'
down_revision = '943625ce57ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('recomend_username', sa.Integer(), nullable=True))
    op.drop_constraint('tasks_ibfk_3', 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'users', ['recomend_username'], ['username'])
    op.drop_column('tasks', 'recomend_user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('recomend_user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key('tasks_ibfk_3', 'tasks', 'users', ['recomend_user_id'], ['id'])
    op.drop_column('tasks', 'recomend_username')
    # ### end Alembic commands ###
