"""empty message

Revision ID: e072f4e0d899
Revises: 
Create Date: 2020-06-11 17:14:32.074613

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e072f4e0d899'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('mark', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('available_actions', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('our_percent', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('top_demand', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('projects', 'top_demand')
    op.drop_column('projects', 'our_percent')
    op.drop_column('projects', 'available_actions')
    op.drop_column('profiles', 'mark')
    # ### end Alembic commands ###
