"""empty message

Revision ID: f7f8be7652be
Revises: 9ef5545976c2
Create Date: 2020-08-25 17:09:30.464144

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f7f8be7652be'
down_revision = '9ef5545976c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contracts', 'project_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.alter_column('contracts', 'task_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=True)
    op.drop_constraint('contracts_ibfk_3', 'contracts', type_='foreignkey')
    op.create_foreign_key(None, 'contracts', 'projects', ['project_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contracts', type_='foreignkey')
    op.create_foreign_key('contracts_ibfk_3', 'contracts', 'tasks', ['project_id'], ['id'])
    op.alter_column('contracts', 'task_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    op.alter_column('contracts', 'project_id',
               existing_type=mysql.INTEGER(display_width=11),
               nullable=False)
    # ### end Alembic commands ###
